Presentation/Controllers/AnimalController.cs
using Presentation.ViewModel;
using System.Collections.Generic;
using System.Web.Mvc;
using Util.EndPoint;
using Util.WebApi;

namespace Presentation.Controllers
{
    public class AnimalController : Controller
    {
        // GET: Animal
        public ActionResult List()
        {
            List<AnimalVM> animalVMs = WebApiClient.Build().Get<List<AnimalVM>>(EndPoints.Animals, null);
            return View(animalVMs);
        }

        public ActionResult Create(int? id)
        {
            AnimalVM animal = new AnimalVM();
            animal.Races = WebApiClient.Build().Get<List<RaceVM>>(EndPoints.Races, null);

            if (id != null)
            {
                animal = WebApiClient.Build().Get<AnimalVM>(EndPoints.Animals, id);
            }

            return View(animal);
        }

        public ActionResult Delete(int id)
        {
            WebApiClient.Build().Delete<AnimalVM>(EndPoints.Animals, id);

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Create(AnimalVM animalVM)
        {
            if (animalVM.Id > 0)
                WebApiClient.Build().Put(EndPoints.Animals, animalVM.Id, animalVM);
            else
                WebApiClient.Build().Post(EndPoints.Animals, animalVM);

            return RedirectToAction("List");
        }
    }
}

Presentation/Controllers/CityController.cs
using Presentation.ViewModel;
using System.Collections.Generic;
using System.Web.Mvc;
using Util.EndPoint;
using Util.WebApi;

namespace Presentation.Controllers
{
    public class CityController : Controller
    {
        // GET: City
        public ActionResult List()
        {
            List<CityVM> cities = WebApiClient.Build().Get<List<CityVM>>(EndPoints.Cities, null);
            return View(cities);
        }

        public ActionResult Create(int? id)
        {
            CityVM city = new CityVM();

            if (id != null)
            {
                city = WebApiClient.Build().Get<CityVM>(EndPoints.Cities, id);
            }
                
            return View(city);
        }

        public ActionResult Delete(int id)
        {
            WebApiClient.Build().Delete<CityVM>(EndPoints.Cities, id);

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Create(CityVM cityVM)
        {
            if (cityVM.Id > 0)
                WebApiClient.Build().Put(EndPoints.Cities, cityVM.Id, cityVM);
            else
                WebApiClient.Build().Post(EndPoints.Cities, cityVM);

            return RedirectToAction("List");
        }
    }
}

Presentation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Presentation/Controllers/RaceController.cs
using Presentation.ViewModel;
using System.Collections.Generic;
using System.Web.Mvc;
using Util.EndPoint;
using Util.WebApi;

namespace Presentation.Controllers
{
    public class RaceController : Controller
    {
        // GET: Race
        public ActionResult List()
        {
            List<RaceVM> races = WebApiClient.Build().Get<List<RaceVM>>(EndPoints.Races, null);
            return View(races);
        }

        public ActionResult Create(int? id)
        {
            RaceVM race = new RaceVM();

            if (id != null)
            {
                race = WebApiClient.Build().Get<RaceVM>(EndPoints.Races, id);
            }

            return View(race);
        }

        public ActionResult Delete(int id)
        {
            WebApiClient.Build().Delete<RaceVM>(EndPoints.Races, id);

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Create(RaceVM raceVM)
        {
            if (raceVM.Id > 0)
                WebApiClient.Build().Put(EndPoints.Races, raceVM.Id, raceVM);
            else
                WebApiClient.Build().Post(EndPoints.Races, raceVM);

            return RedirectToAction("List");
        }
    }
}

Presentation/Views/Animal/Create.cshtml
@model Presentation.ViewModel.AnimalVM
@{
    ViewBag.Title = "Create";
}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (Html.BeginForm("Create", "Animal", FormMethod.Post))
        {
            @Html.Label("Nome: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Nome do animal" }) <br />

            @Html.Label("Raça: ", new { @class = "col-form-label" })
            @Html.DropDownListFor(x => x.Race.Id, Model.Races.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString(), Selected = x.Id.ToString().Equals(Model.Race.Id.ToString()) }), new { @class = "form-control"})

            @Html.Label("Gênero: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.Gender, new { @class = "form-control", @placeholder = "País do gênero" }) <br />

            @Html.Label("Observação: ", new { @class = "col-form-label" })
            @Html.TextAreaFor(m => m.Note, new { @class = "form-control" }) <br />

            <button type="submit" class="btn btn-primary">Salvar</button>
        }
    </div>
</div>

Presentation/Views/Animal/List.cshtml
@model List<Presentation.ViewModel.AnimalVM>
@{
    ViewBag.Title = "List";
}
<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="col-sm-11 col-md-11 col-lg-11">

        <h2>Animais</h2>
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1">
        <br />
        <a href='@Url.Action("Create", "Animal")'></a>
        <input type="button" class="btn btn-primary" value='Novo animal' />
        </a>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <td>Nome</td>
                    <td>Raça</td>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var field in Model)
                    {
                        <tr>
                            <th>@field.Name</th>
                            <th>@field.Race.Name</th>
                            <th>@Html.ActionLink("Editar", "Create", "Animal", new { id = field.Id }, null)</th>
                            <th>@Html.ActionLink("Deletar", "Delete", "Animal", new { id = field.Id }, null)</th>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<br />
<br />

Presentation/Views/City/Create.cshtml
@model Presentation.ViewModel.CityVM

@{
    ViewBag.Title = "Criação de cidade";
}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (Html.BeginForm("Create", "City", FormMethod.Post))
        {
            @Html.Label("Nome: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Nome da cidade" }) <br />

            @Html.Label("UF: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.UF, new { @class = "form-control", @placeholder = "UF da cidade" }) <br />

            @Html.Label("País: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.Country, new { @class = "form-control", @placeholder = "País da cidade" }) <br />

            @Html.Label("Codigo municipal: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.MunicipalCode, new { @class = "form-control", @placeholder = "Código municipal da cidade" }) <br />

            <button type="submit" class="btn btn-primary">Salvar</button>
        }
    </div>
</div>

Presentation/Views/City/List.cshtml
@model List<Presentation.ViewModel.CityVM>
@{
    ViewBag.Title = "List";
}

    <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="col-sm-11 col-md-11 col-lg-11">

            <h2>Cidades</h2>
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
            <br />
            <a href='@Url.Action("Create", "City")'></a>
            <input type="button" class="btn btn-primary" value='Nova cidade' />
            </a>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-12">
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <td>Código municipal</td>
                        <td>Nome</td>
                        <td>País</td>
                        <td>UF</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var field in Model)
                    {
                        <tr>
                            <th>@field.MunicipalCode</th>
                            <th>@field.Name</th>
                            <th>@field.Country</th>
                            <th>@field.UF</th>
                            <th>@Html.ActionLink("Editar", "Create", "City", new { id = field.Id }, null)</th>
                            <th>@Html.ActionLink("Deletar", "Delete", "City", new { id = field.Id }, null)</th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
<br />
<br />

Presentation/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Presentation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Presentation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Presentation/Views/Race/Create.cshtml
@model Presentation.ViewModel.RaceVM
@{
    ViewBag.Title = "Create";
}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (Html.BeginForm("Create", "Race", FormMethod.Post))
        {
            @Html.Label("Nome: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Nome da raça" }) <br />

            @Html.Label("Espécie: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.Specie, new { @class = "form-control", @placeholder = "UF da espécie" }) <br />

            @Html.Label("Porte: ", new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.Size, new { @class = "form-control", @placeholder = "Porte da raça" }) <br />

            @Html.Label("Observação: ", new { @class = "col-form-label" })
            @Html.TextAreaFor(m => m.Note, new { @class = "form-control" }) <br />

            <button type="submit" class="btn btn-primary">Salvar</button>
        }
    </div>
    </div>

Presentation/Views/Race/List.cshtml
@model List<Presentation.ViewModel.RaceVM>
@{
    ViewBag.Title = "List";
}

<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="col-sm-11 col-md-11 col-lg-11">

        <h2>Raças</h2>
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1">
        <br />
        <a href='@Url.Action("Create", "Race")'></a>
        <input type="button" class="btn btn-primary" value='Nova raça' />
        </a>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <td>Nome</td>
                    <td>Espécie</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var field in Model)
                {
                    <tr>
                        <th>@field.Name</th>
                        <th>@field.Specie</th>
                        <th>@Html.ActionLink("Editar", "Create", "Race", new { id = field.Id }, null)</th>
                        <th>@Html.ActionLink("Deletar", "Delete", "Race", new { id = field.Id }, null)</th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<br />
<br />

Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>